# -*- coding: utf-8 -*-

SPIDER_STATIC_PAGE = 0
SPIDER_DYNAMIC_PAGE = 1
SPIDER_JSON_PAGE = 2

SPIDER_DATA_FORMAT_TABLE = 0
SPIDER_DATA_FORMAT_JASON = 1

SPIDER_FIELD_TYPE_STRING = 0
SPIDER_FIELD_TYPE_NUMBER = 1