FROM shepherd-base:latest
ENV SHEPHERD_BASE=/home/shepherd
WORKDIR $SHEPHERD_BASE/shepherd_0.1.0
EXPOSE 8888
# CMD echo "Shepherd container is running ..." && while true; do sleep 10; done
SHELL ["/bin/bash", "-c"]
CMD ["./start-shepherd.sh"]

